export const elements = {
    libraryContainer: document.querySelector("#library-container"),
    songTitle: document.querySelector("#song-title"),
    songArtist: document.querySelector("#song-artist"),
    trackContainer: document.querySelector("#tracks-container"),
    playerControls: document.querySelector("#player-controls"),
    sliderProgress: document.querySelector("#slider-progress"),
    containerLyrics: document.querySelector(".container-lyrics"),
    libraryScreen: document.querySelector("#library-screen"),
    playerScreen: document.querySelector("#player-screen"),
    backButton: document.querySelector("#back-button"),
    card: document.querySelector("#container-preview"),
    coverCard: document.querySelector("#preview-cover"),
    titleCard: document.querySelector("#preview-title"),
    artistCard: document.querySelector("#preview-artist"),
    durationCard: document.querySelector("#preview-duration"),
    tomAcima: document.querySelector("#tom-acima"),
    tomAbaixo: document.querySelector("#tom-abaixo"),
    tonalidadeAtual: document.querySelector("#tonalidade-atual"),
    play: document.querySelector("#play"),
    pause: document.querySelector("#pause"),
    stop: document.querySelector("#stop")
};